apiVersion: v1
kind: ServiceAccount
metadata:
  name: where-for-dinner-gemfire-secret-template-reader
  namespace: service-instances
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: where-for-dinner-gemfire-secret-template-reader
  namespace: service-instances
rules:
- apiGroups:
  - '*'
  resources:
  - secrets
  - services
  - pods
  - gemfireclusters
  verbs:
  - get
  - list
  - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: where-for-dinner-gemfire-secret-template-reader
  namespace: service-instances
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: where-for-dinner-gemfire-secret-template-reader
subjects:
- kind: ServiceAccount
  name: where-for-dinner-gemfire-secret-template-reader
---
apiVersion: secretgen.carvel.dev/v1alpha1
kind: SecretTemplate
metadata:
  name: cache-where-for-dinner-gemfire-secret
  namespace: service-instances
spec:
  serviceAccountName: where-for-dinner-gemfire-secret-template-reader
  inputResources:
  - name: gemfire-locator-service
    ref:
      apiVersion: v1
      kind: Service
      name: cache-where-for-dinner-locator
  - name: gemfire-locator-pod
    ref:
      apiVersion: v1
      kind: Pod
      name: cache-where-for-dinner-locator-0
  template:
    metadata:
      labels:
        app.kubernetes.io/component: gemfire
        app.kubernetes.io/instance: cache-where-for-dinner
        services.apps.tanzu.vmware.com/class: where-for-dinner-gemfire
    stringData:
      host: $(.gemfire-locator-pod.spec.hostname).$(.gemfire-locator-pod.spec.containers[?(@.name=="locator")].env[?(@.name=="LOCATOR_SERVICE")].value)
      port: $(.gemfire-locator-service.spec.ports[?(@.name=="locator")].port)
      provider: vmware
      type: gemfire
---
apiVersion: services.apps.tanzu.vmware.com/v1alpha1
kind: ClusterInstanceClass
metadata:
  name: gemfire-where-for-dinner
spec:
  description:
    short: Where for Dinner GemFire
  pool:
    kind: Secret
    labelSelector:
      matchLabels:
        services.apps.tanzu.vmware.com/class: where-for-dinner-gemfire
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: where-for-dinner-gemfire-secret-reader
  labels:
    servicebinding.io/controller: "true"
rules:
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - get
  - list
  - watch
